import {StyleSheet, Dimensions, Platform} from 'react-native';

const HEADER_MAX_HEIGHT = 300;

export default StyleSheet.create({
  container: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
  },
  bar: {
    flex: 1,
    paddingTop: 15,
    alignItems: 'center',
  },
  scroll: {
    backgroundColor: 'black',
    height: Dimensions.get('screen').height,
  },
  searchbarinput: {
    backgroundColor: 'white',
  },
  button: {
    borderBottomLeftRadius: 10,
    borderBottomRightRadius: 10,
    borderTopLeftRadius: 10,
    borderTopRightRadius: 10,
    backgroundColor: '#990000',
    marginRight: 15,
    elevation: 1,
    zIndex: 1,
  },
  fill: {
    flex: 1,
    backgroundColor: 'black',
  },
  content: {
    flex: 1,
  },
  contact: {
    backgroundColor: 'black',
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
  },
  header: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    backgroundColor: '#990000',
    overflow: 'hidden',
    height: HEADER_MAX_HEIGHT,
    elevation: 4,
    shadowOffset: {width: 5, height: 5},
    shadowColor: 'black',
    shadowOpacity: 1,
    shadowRadius: 10,
  },
  backgroundImage: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    width: null,
    height: HEADER_MAX_HEIGHT,
    resizeMode: 'cover',
  },
  bar: {
    backgroundColor: 'transparent',
    marginTop: Platform.OS === 'ios' ? 28 : 38,
    height: 32,
    alignItems: 'center',
    justifyContent: 'center',
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
  },
  title: {
    color: 'white',
    fontSize: 18,
  },
  scrollViewContent: {
    paddingTop: Platform.OS !== 'ios' ? HEADER_MAX_HEIGHT + 20 : 20,
    paddingBottom: 30,
  },
  row: {
    height: 40,
    margin: 16,
    backgroundColor: '#D3D3D3',
    alignItems: 'center',
    justifyContent: 'center',
  },
  searchbar: {
    top: 0,
    backgroundColor: 'transparent',
    width: Dimensions.get('screen').width * 0.75,
    alignItems: 'center',
    borderBottomColor: 'transparent',
    borderTopColor: 'transparent',
  },
  item: {
    borderTopLeftRadius: 10,
    borderTopRightRadius: 10,
    borderBottomRightRadius: 10,
    borderBottomLeftRadius: 10,
    backgroundColor: '#990000',
    padding: 20,
    marginVertical: 8,
    marginHorizontal: 16,
  },
  name: {
    fontSize: 32,
    color: '#ebe6e6',
  },
  address: {
    fontSize: 16,
    color: '#ebe6e6',
  },
  searchbarinputtext: {
    color: 'black',
  },
  dialogviewouter: {
    // flexDirection: 'row',
    paddingTop: 5,
    paddingBottom: 10,
  },
  dialogviewinner: {
    flexDirection: 'row',
    paddingRight: 150,
    paddingTop: 10,
    elevation: 1,
    zIndex: 5,
  },
  dialogviewtext: {
    fontSize: 18,
    paddingBottom: 8,
  },
  hometextoverlay: {
    fontSize: 40,
    color: 'white',
    // fontFamily: 'Roboto',
    // fontWeight: 'bold',
    marginLeft: 50,
    marginTop: 100,
  },
  map: {
    height: 375,
    width: 375,
    justifyContent: 'center',
    alignItems: 'center',
  },
  mapContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    marginTop: 15,
  },
  containerChangeEmail: {
    flex: 1,
    backgroundColor: '#000',
  },
  greeting: {
    marginTop: 28,
    color: '#ccc',
    fontSize: 28,
    fontWeight: '400',
    textAlign: 'center',
  },
  form: {
    marginTop: 28,
    marginBottom: 48,
    marginHorizontal: 30,
  },
  inputTitle: {
    color: '#ccc',
    fontSize: 10,
    textTransform: 'uppercase',
  },
  input: {
    borderBottomColor: '#ccc',
    borderBottomWidth: StyleSheet.hairlineWidth,
    height: 40,
    fontSize: 15,
    color: '#eee',
  },
  buttonChangeEmail: {
    marginHorizontal: 30,
    backgroundColor: '#f55',
    borderRadius: 10,
    height: 52,
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: 20,
  },
  imageChangeEmail: {
    alignSelf: 'center',
    width: 400,
    height: 128,
    marginTop: 64,
  },
  containerLogin: {
    flex: 1,
    backgroundColor: '#000',
  },
  greetingLogin: {
    marginTop: 28,
    color: '#ccc',
    fontSize: 28,
    fontWeight: '400',
    textAlign: 'center',
  },
  formLogin: {
    marginTop: 28,
    marginBottom: 48,
    marginHorizontal: 30,
  },
  inputTitleLogin: {
    color: '#ccc',
    fontSize: 10,
    textTransform: 'uppercase',
  },
  inputLogin: {
    borderBottomColor: '#ccc',
    borderBottomWidth: StyleSheet.hairlineWidth,
    height: 40,
    fontSize: 15,
    color: '#eee',
  },
  buttonLogin: {
    marginHorizontal: 30,
    backgroundColor: '#f55',
    borderRadius: 4,
    height: 52,
    alignItems: 'center',
    justifyContent: 'center',
  },
  imageLogin: {
    alignSelf: 'center',
    width: 400,
    height: 128,
    marginTop: 64,
  },
  header_2: {
    height: 100,
    backgroundColor: '#990000',
    overflow: 'hidden',
    shadowColor: 'black',
    elevation: 4,
    shadowOpacity: 1,
    shadowRadius: 10
  }
});
